import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                {children}
                {/* <script src="https://cmp.osano.com/Azz8BxUZW6uC96GYa/2f59f869-5484-4eb4-9ada-6f79da286f9e/osano.js" async></script> */}
                <script src="https://cmp.osano.com/Azz8BxUZW6uC96GYa/a2b25a48-61db-491a-beb0-1e1384fc91d2/osano.js" async></script>
            </body>
        </html>
    );
}
